MerlinLabs/styled-material-components

- pages/buttons.js
- pages/cards.js
- pages/index.js
- src/components/Button.js
- src/components/Card/Actions.js
- src/components/Card/Avatar.js
- src/components/Card/Card.js
- src/components/Card/HorizontalBlock.js
- src/components/Card/Media.js
- src/components/Card/MediaItem.js
- src/components/Card/Primary.js
- src/components/Card/Subtitle.js
- src/components/Card/SupportingText.js
- src/components/Card/Title.js
- src/components/Card/index.js
- src/mixins/typography.js
- src/theme/defaultTheme.js
add all pieces of the card as separate components
add mixins for typography
add demo page for Card
move index page to Button page
add new values to defaultTheme.js
> feat(card): add material card

- pages/cards.js
- src/components/Button.js
- src/components/Card/Actions.js
- src/components/Card/Avatar.js
- src/components/Card/Card.js
- src/components/Card/HorizontalBlock.js
- src/components/Card/Media.js
- src/components/Card/MediaItem.js
- src/components/Card/Primary.js
- src/components/Card/Subtitle.js
- src/components/Card/SupportingText.js
- src/components/Card/Title.js
1. Add static classes to all card components
2. Update styles
3. Add new card demos
4. Add support for vertical actions
> feat(Card): Add missing card features

- package.json
- yarn.lock
Updates dependencies to the latest versions.
Resolve #8
> build(Dependencies): Update

- pages/cards.js
- src/components/Card/index.js
Fix export pattern in Card/index so that they can be imported from Card/index on the cards page.
Also, remove unused typography import
In the process fix a typo in the Card export that prevented me from building and publishing
> fix(Card): fix export/import

- package.json
- src/index.js
Exports components added after initial release.
> Export other components

- package.json
- src/components/TextField.js
Resolve warnings by renaming display prop to show prop, and by
removing the unnecessary autofill prop from Input.
> fix(TextField): resolve warnings

- package.json
- src/components/Button.js
* Imports react so the button component will not error on being imported in a third party library.
* Bumps the version
* Prettier changes
> Fix button

- package.json
- pages/text-fields.js
- src/components/TextField.js
Modifies the TextField to accept either a React component or a string, and adds it into the demo.
Can check it out [here](https://docs-jsuyrkqezy.now.sh/)
> Accept component

- package.json
- src/.babelrc
- yarn.lock
> Export extensions transform

- pages/buttons.js
- src/components/Button.js
I passed down the props, so that we could fire onClick events, and
other button props in the future.
I thought it would be beneficial to pass all the props through to the `button`? Is this a good idea?
> feat(Button): Passes props

- package.json
- src/components/Button.js
This allows props to be safeguarded by an acceptableProps object.
> feat(Button): Safeguards props

- package.json
- src/components/Tabs/index.js
> Tabs export

- package.json
- src/components/Card/Actions.js
- src/components/Card/Avatar.js
- src/components/Card/Card.js
- src/components/Card/HorizontalBlock.js
- src/components/Card/Media.js
- src/components/Card/MediaItem.js
- src/components/Card/Primary.js
- src/components/Card/Subtitle.js
- src/components/Card/SupportingText.js
- src/components/Card/Title.js
- src/components/Tabs/InkBar.js
- src/components/Tabs/Tabs.js
- Fixes Cards components bug (missing import)
- Adds ability to customize InkBar color in Tabs
> Small fixes

- package.json
- src/index.js
Exports the default theme so it can be imported.
> Expose default theme

- src/components/TextField.js
rm vestigial props from div. This also resolves attributes warnings
There are also some prettier changes.
> fix(TextField): rm div props

- src/components/Dialog/Dialog.js
- src/components/Slider/FocusRing.js
- src/components/Slider/SliderDisabledWrapper.js
- src/components/Slider/SliderTrack.js
- src/components/Slider/Thumb.js
- src/components/Slider/TrackValue.js
- src/components/Slider/Trackline.js
- src/components/Slider/ValueTrack.js
- src/components/Table/Datum.js
- src/components/Table/Row.js
- src/components/Table/Table.js
- src/components/Table/Title.js
- src/mixins/typography.js
- src/theme/makeMaterialSliderTheme.js
> fix(Linting): Fix errors

- package.json
- src/index.js
Exports the newly added components so they can be used -_-
> Export new components

- src/components/TextField.js
Synchronizes the subcomponents on the question of whether or not the
field has an error.
> fix(Textfield): Simplify error api

- pages/divider.js
- pages/index.js
- pages/lists.js
- src/components/Divider.js
- src/components/List/ListItem.js
- src/components/List/ListItemText.js
- src/index.js
- src/theme/ThemeProvider.js
Adds the divider component as a standalone component as well as an
option for listitem.
Preview app here: https://docs-irbmjcdpwv.now.sh
> feat(Divider): Add divider

- pages/appbar.js
- pages/index.js
- src/components/Appbar.js
- src/index.js
First pass at Appbar. Currently accepts title props.
TODO:
[] NavIcon
[] Action icons
[] Menu icon
Resolves #103 
Demo: https://docs-iydvzigxai.now.sh
> feat(Appbar): Add basic Appbar with title

- .circleci/config.yml
- package.json
- src/index.js
- yarn.lock
Export Drawer component in index.js
> fix(Drawer): Export Drawer component

- package.json
- src/components/TextField.js
Fix 'Cannot read property 'scrollHeight' of undefined' error received
after compilation
> fix(TextField): Fix scrollHeight error

- pages/cards.js
- src/components/Card/Card.js
This adds a prop for Cards to control whether it elevates more on hover.
Link: https://docs-dyaarlwenq.now.sh/
> feat(Card): Add hover prop for elevation

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Add contributing guide, Code of Conduct, and update README
> docs(Contributing Guide): Add Contributing Guide

- AUTHORS
- CONTRIBUTING.md
Small change but it should be `Anyone` instead of `Any one` in this particular context :)
> docs(Contributing Guide): Adjust grammar

- AUTHORS
- src/components/Button.js
Modified: 
* Button
Fixed button text color to not match the background color
of the raised and flat buttons. 
Issues: none
> Fix(button): fix button styles

- AUTHORS
- pages/bottomsheets.js
- pages/index.js
- src/components/BottomSheet.js
[View Here](https://docs-exsmtmyrql.now.sh)
Bottomsheets can be either modal or persistent.
To specify a modal sheet, pass a "modal" prop.
TODO:
Add list style bottomsheet
Add list style bottomsheet with header
Add grid style bottomsheet
Add grid style bottomsheet with header
Make persistent sheet scrollable container for content
Implement mobile responsive heights and widths
> feat(BottomSheet): Add BottomSheet

- package.json
- src/components/Card/Card.js
Modified: 
• Card
I added the "hover" styles to match the spec whenever 
someone hovers their mouse over the card component.
I made sure that it only effects the cards with the hover 
property in them. 
Issues: none
> refactor card styles

- AUTHORS
- pages/index.js
- pages/switches.js
- src/components/Avatar.js
- src/components/Switch/Switch.js
- src/components/Switch/SwitchThumb.js
- src/components/Switch/SwitchTrack.js
https://docs-amnypfkmsw.now.sh/
fixes #34
> Switch feature and Avatar.js bug fix

- pages/appbar.js
- src/components/Appbar.js
Adds a navIcon prop to optionally pass in for added functionality determined by the user! (else renders the placeholder as before)
https://docs-kujyejzdul.now.sh
> add NavIcon support for Appbar

- pages/buttons.js
- src/components/FloatingActionButton.js
Create FloatingActionButton. Resolves #18 
Demo: https://docs-kmzwbqrntp.now.sh/
> feat(FloatingActionButton): Create FloatingActionButton

- src/components/Avatar.js
- src/components/Image.js
Fix import statements for Image and Circular files in Avatar component
> fix(Avatar): Fix import statements

- src/components/Card/Card.js
- src/components/Card/Primary.js
React was throwing a warning on passing a non-boolean attribute to the component. This fixes it by not passing it through the CardComponent, and only the Card.
Note: This also has a slight fix to the import statements of Image in Avatar.
> fix(Card): Fix hover warning

- package.json
- src/components/Avatar.js
Fixes the react undefined issue when using the SMC module in a non
next-build env
> fix(Avatar): Import React

- pages/appbar.js
- src/components/Drawer.js
Modified: 
* Drawer
I re-did the original PR - this one doesn't modify the persistent drawer,
but adds support and styles for a temporary drawer. Thanks @martahj for showing
the correct implementation of how different drawers should be like!
link => https://docs-cdikxdudmw.now.sh!
> Add temporary drawer

- AUTHORS
- pages/text-fields.js
- src/components/TextField.js
Add ability to reset a text field to it's
default value from the parent component.
Fixes #163
> feat(TextField): Add Reset Functionality

- pages/tabs.js
- src/components/Tabs/Tabs.js
- src/components/Tabs/index.js
Exports subcomponents so they can be styled
PR app: https://docs-etrgspdode.now.sh
> refactor(Tabs): Export subcomponents

- pages/tabs.js
- src/components/Tabs/Tabs.js
Implements controlled tabs
Now link https://docs-totoujivtt.now.sh
> feat(Tabs): Allow controlled

- pages/index.js
- pages/lists.js
- pages/menus.js
- src/components/Menu/Menu.js
- src/components/Menu/MenuItem.js
- src/components/Menu/MenuList.js
- src/enhancers/withRipple.js
- src/index.js
First pass at menu component. This component is accessible and
navigable by keyboard events and usable in a form via  hidden
select/option elements
Resolve #27 
Demo: https://docs-lqtopesdba.now.sh
> feat(Menu): Add base menu component

- src/components/TextField.js
Set the value to the nextProps default value on reset.
> fix(TextField): Set current defaultValue

- .gitignore
- src/components/Menu/MenuList.js
- src/components/Menu/index.js
> fix(Menu Index): Fix Menu index.js

- AUTHORS
- pages/lists.js
- src/components/List/ListSubheader.js
- src/components/List/index.js
Adding support for Subheaders in the List component. Supports both default and primary color options by passing in a primary prop.
Does not currently support alignment for the case when a floating action button is left aligned.
https://docs-bscxeohlhj.now.sh
> feat(List): Add ListSubheader to List component

- pages/chips.js
- src/components/Chip.js
Added elevation to focused chips + some minor refactoring
https://docs-nulagmgepu.now.sh
> feat(Chip): add elevation on focus

- package.json
- pages/tables.js
- src/components/Checkbox.js
- src/components/Table/Datum.js
- src/components/Table/Header.js
- src/components/Table/Row.js
- src/components/Table/Table.js
- src/components/Table/Title.js
- src/components/Table/naturalSort.js
- src/icons/ArrowUpwardPath.js
- src/icons/UpwardArrowPath.js
- src/icons/icons.js
- src/theme/ThemeProvider.js
- yarn.lock
Added checkboxes and filtering to the table component. See the new notes on the deployment below!
Very excited to share this. Tear it up! 
(be sure to check the tables page below for usage of the new props!)
https://docs-ibzdgzpvwa.now.sh
> feat(Table): Checkboxes + Sorting!

- pages/text-fields.js
- src/components/TextField.js
Adds charLimit prop to text fields
Now demo: https://docs-aufwoerikv.now.sh/text-fields/
> feat(Text Input): Add Char Limit

- pages/tables.js
- src/components/Table/Search.js
- src/components/Table/Table.js
- src/components/TextField.js
- src/icons/icons.js
Adds Search functionality to the table. This comes in the form of a styled search that fires an onSearch prop that the user provides!
Wanted to get feedback on how this guy should work. I'm having a hard time finding design specs for material tables with search components. therefore I decided to make this as best i could.
https://docs-jdfbczswgo.now.sh/tables/
> feat(Table): Add Search

- pages/tables.js
- src/components/Table/Datum.js
- src/components/Table/Table.js
Return null for datum with no children
(see faked pagination for an example!)
Fix checkbox header float left on fullWidth
https://docs-icojuhrnkl.now.sh/tables/
> fix(Tables): Handle Empty Datum

- pages/text-fields.js
- src/components/TextField.js
Add text area with border
https://material.io/guidelines/components/text-fields.html#text-fields-field-types
Demo: https://docs-scyqspdjkm.now.sh/text-fields/
Fixes #198 
Fixes #190
> feat(Textarea): Add textarea with border

- pages/text-fields.js
- src/components/TextField.js
fixes the additional * and the error / help text overlap.
https://docs-ylaawygbdl.now.sh/text-fields
> fix(textfield): fix * and errorText

- src/components/Tabs/Tab.js
- src/components/Tabs/Tabs.js
Fixes styled exports on the tab component so it exports the styled
versions of everything.
> fix(Tabs): Fix styled

- pages/dialog.js
- src/components/Dialog/Dialog.js
This allows us to pass in the onClose handler from the parent.
https://docs-qjyesojtti.now.sh
> fix(Dialog): Control onClose

- CHANGELOG.md
- package.json
Now called Toolbar!
* Added MVP Toolbar Component - @brad-decker - 07942cb77e22153efdec737d978d7943ff12d79d
* Refactor Checkbox and add CheckMark and indeterminate mark - @petegivens - 2bd044d1dc0d00626a0febc34e74d96142912fa4
* Control onClose - @dekkofilms - 26d992921ba3fb7564d52443c4ea948001afe902
* Fixed overlay to correct position - @ashwoodall - 399ae855804972d6396e0d99242ae65810c09d86
* Removed marginLeft from hr - @petegivens - 091e1ec3191ce2d596b6ad265bb0aafed02c99eb
* Update styles - @ashwoodall  - 8afae5a5e9b90e2aaa9be3a8d51088a7e36f4431
* Added close and menu icons - @brad-decker - 5c3c770a018ec2fe497877dfd2e039701b529a72
* Add anchor element to attach to - @dekkofilms - c63e99f1f52b1f69c30b2baa4eca7853f7e95f18
* Add functional HoCs - @brad-decker - …
> build(Release): Alpha 44

- pages/text-fields.js
- src/components/TextField.js
This passes in the name prop to the input.
> fix(TextField): Pass in name prop

- pages/index.js
- pages/tooltip.js
- src/components/Portal/Portal.js
- src/components/Portal/index.js
- src/components/Tooltip.js
- src/index.js
Builds out an initial tooltip component
Resolve #47 
Now link: https://docs-kjhyzertdn.now.sh
> feat(Tooltip): Initial implementation

- pages/dialog.js
- src/components/Dialog/Dialog.js
This adds a full screen dialog component. These are intended to
facilitate complex user interactions on mobile that require the full
screen.
https://docs-cdybiwzkwb.now.sh
> feat(fullscreendialog): add fullscreen dialog

- pages/text-fields.js
- src/components/DropdownMenu.js
- src/components/TextField.js
Refactor DropdownMenu component
to handle callbacks on item selection
Link => https://docs-bruvuxsidn.now.sh
> Refactor(DropdownMenu)

- src/components/Tabs/Tabs.js
Exports Inkbar and TabBarContainer from the Tabs file.
> feat(Tabs): Export Inkbar and TabBarContainer

- package.json
* Exports generateBreakpoint function - @AriLFrankel - [cc9160e](cc9160e7ee65b92d195558f46abe232c1e6a1fec)
* Makes onClose controlled - @dekkofilms - [26d9929](26d992921ba3fb7564d52443c4ea948001afe902)
* Adds fullscreen Dialog component - @AriLFrankel - [89547bd](89547bdb411f9f02ae7d337f2c210474e67f4558)
* Allows select handler callback to be passed to component - @ceciliamvrie - [c10949e](c10949e471efc38cd378c416668f66b11bee2d4b)
* Fixes sortby bug - @danielstclair - [742fc90](742fc9081c4ac5daefc993766f6e456742ee2a07)
* Comment on this PR by @BennettStaley : *"Noted issue: While this functions perfectly normally inside SMC context, once SMC is installed as a module it fails to bind context. Reminiscent of the react import issue we had before."*
* Adds onRowChange callback - …
> Version 0.0.45

- src/icons/ArrowBackPath.js
- src/icons/ArrowForwardPath.js
- src/icons/icons.js
> feat(Icons): Add Icons

- src/components/Table/Table.js
This fixes the numerical header columns to be aligned on the right side with the table cells below.
https://docs-qaarejakfw.now.sh
> fix(Table): Fix numerical headers

- src/components/Menu/MenuItem.js
- src/components/Menu/MenuList.js
Added the ability to tab through the MenuList
without tabbing out of the Menu
new link =>https://docs-uxodthnqtk.now.sh!
> refactor(MenuList): Add tab scrolling

- src/components/Dialog/Dialog.js
This allows the user to close the modal on esc
key press.
> feat(Dialog): Close on esc key press

- pages/text-fields.js
- src/components/TextField.js
- src/theme/defaultTheme.js
This has two commits:
This checks if the input isControlled. Also making sure if the input is controlled that the floating label would work if the value passed in has a string with the length greater than 0.
This adds into the default theme the text field color that we can now control from the theme object.
Now link: https://docs-xtngblqdhp.now.sh/
> Textfield changes

- src/mixins/transition.js
Mixin to add easing and duration css properties.
Did not create a new build, as it is not currently being used.
Could use `platform` to detect current platform, but would need a list of platform os's that need to be supported.
> enhancement(Transitions): Mixin for duration and easing

- src/index.js
> feat(Transition mixin): Exports

- package.json
- src/components/TextField.js
Fixes a bug with the textfield  that was released in 0.0.48. Also updates to 0.0.49, which has already been published 😅
> Textfield bug

- package.json
* exports new icons - @petegivens - d42a8c82d40a32c8c30f147f516a550ab6cdffb3
* exports these - @martahj - 83f7f4a59fef20d01aeed631a8893b65139a98e0
> Version 0.0.50

- src/components/Table/Table.js
Fix issue where table arrows weren't rotating when providing an onSort
prop.
> fix(Table): Fix Table Arrows

- pages/avatars.js
- pages/index.js
- src/components/Avatar.js
This PR adds the ability for a name prop to be passed to Avatar and creates initials if an image src is not defined. It handles passed first + last name, first (single) name, initials (2 chars), or no name prop.
> feat(Avatar): Add initials

- pages/menus.js
- src/components/Menu/Menu.js
Open menu to where there is space for it. If there is not room for it below open vertically. If there is not room to the right open to the left.
> feat(menu): open to space

- pages/tooltip.js
- src/components/Tooltip.js
- yarn.lock
Made some small style edits to the tooltip component.
> Refactor(Tooltip): Restyle Tooltip

- pages/chips.js
- src/components/Chip.js
- this adds a `removeIcon` prop to Chip
- if passed in, it will replace the default icon (x)
- will only appear if chips have either `removable` or `onDelete` props
> feat(chip): accept removeIcon prop

- src/components/BottomSheet.js
This makes the bottomsheet a position fixed element.
> fix(Bottomsheet): Make position fixed

- src/components/BottomSheet.js
Adds classname to bottom-sheet component
> fix(BottomSheet): Add classname

- .prettierrc.yaml
- pages/menus.js
- src/components/Menu/Menu.js
- Prettier config file added
- Fix menu anchor element
- Check in the menu pages that all varieties of the menu still work
- Resolves an issue found in #315
> Fix anchorEl and prettier config added

- pages/chips.js
- src/components/Chip.js
Implement a chip label render prop.
> feat(Chip): Chip Label Render Prop

- package.json
- src/mixins/transition.js
- yarn.lock
Worked on this with @adonesky1 	
- Fixes Mac import issue by adding fallback to empty string for `platform.os.family`
- n/a
> Mac import issue

- pages/menus.js
- src/components/Menu/Menu.js
- add `fullWidth` prop to Menu component
- if `true`, the width of the menu will be locked to the width of its anchor element.
> feat(Menu): add `fullWidth` prop

- package.json
- src/components/Avatar.js
- src/components/Checkbox.js
- src/components/Slider/SliderTrack.js
- src/components/Snackbar.js
- src/components/Toolbar/Navigation.js
- src/components/Tooltip.js
- yarn.lock
- upgrade to SC 4.1
- updates to the correct usage of `.attrs`
- fix a bug with `Slider` that prevented it from working when rendered inside a Portal
> fixes: Slider and styled-components syntax

- README.md
- Adds build script to initials setup instructions to avoid an error that users who have not built their dist folder would otherwise see
- nothing
> add missing setup instruction
