- package.json
Fixes a typo in the 'clear' script in the package.json preventing the
package from being published.
> build(package.json): Fix typo

- package.json
- pages/text-fields.js
- src/components/TextField.js
Remove the animation from the Hint Text in order to fix jumpy underline thickness
Add a disableFocus feature that disables the focus underline. This will be useful when using a textfield as a search bar.
Also a fair number of cosmetic changes from Prettier.
> fix(TextField): resolve underline jumpiness

- package.json
- pages/tabs.js
- src/components/Tabs/InkBar.js
- src/components/Tabs/Tabs.js
This adds the ability to style the tab navigation
background to a speicfied color. Also, the port
is updated to 8081 for internal convenience.
> feat(Tabs): Style Nav

- src/mixins/typography.js
Updates the typography mixin to use a font-family specified in the
theme if one is provided, and default to Roboto otherwise.
> feat(Typography): Enable font-family override

- src/index.js
Exports withRipple from the mixins folder instead of the nonexistent
decorators folder.
> fix(withRipple export): Export from correct place

- src/components/Snackbar.js
Adds a classname to the snackbar message so it can have its styles
overriden.
> fix(Snackbar): Add class to Message

- pages/text-fields.js
- src/components/TextField.js
Update text area to autoresize when content is added per material specs. Currently works only with single row. TODO: add resize when rows attribute is specified. 
Preview link: https://docs-vaihimcipu.now.sh/
> feat(Textfield autoresize): Add multiline autoresize on text area

- .circleci/config.yml
At first I was going to suggest we change to the recommended yarn installer away from a global npm install, but then I saw that the [Node/carbon](https://github.com/nodejs/docker-node/blob/994f8286cb0efc92578902d5fd11182f63a59869/8/Dockerfile) comes with Yarn pre-installed, so there's no need to install yarn at all.
> ci(yarn): remove unnecessary global installation of yarn in ci container that has yarn already

- AUTHORS
- LICENSE
- package.json
Adds an AUTHORS file modeled after the one in Node (all contributors).
Adds a LICENSE (MIT)
> docs(authors/license): move to root

- pages/checkboxes.js
- pages/index.js
- src/components/Checkbox.js
- src/theme/defaultTheme.js
addresses https://github.com/ConciergeAuctions/styled-material-components/issues/32
Now Link: https://docs-lxkvxelsyq.now.sh/
Checkboxes can be controlled or uncontrolled.
Accepts the following props:
- primary: render in primary theme color
- accent: render in accent theme color (default behavior)
- defaultChecked
- checked: for controlled checkboxes
- disabled
- indeterminate
- onChange: for controlled checkboxes
- value
TODO:
- animations (halp)
- labels
> feat(Checkbox): Add Checkbox

- AUTHORS
- package.json
- scripts/seed-authors.sh
- scripts/update-authors.sh
This introduces a postcommit hook that will automatically update the AUTHORS file.
This will:
- search the AUTHORS file for the email of the committer
- add a line with name <email> for that committer if they are not represented already
This also introduces a `seed-authors` script that will
- output authors by order of first contribution to the AUTHORS file
- filter out repeat entries (unique by email) and commits accidentally added before being associated with a git account
> feat(AUTHORS): scripted AUTHORS

- package.json
- src/components/Tabs/InkBar.js
On load the inkbar flashes to 100% width before shrinking to the
correct width. This is because it passed a value of undefined for the
tabWidth prop. This commit defaults that value to 0 for the tab, so
that it will not display the inkbar until after the width has been
determined.
This is a link to a screen grab of what I'm talking aboutL https://gfycat.com/BlondPossibleAmericancreamdraft
This is a link to this build https://docs-etaviocnju.now.sh, but note that you would need to refresh the tabs page to see the impact of this change, which is not supported.
> fix(inkbar): fix inkbar flash

- src/components/Chip.js
This was leftover from before we added the font-family to the defaultTheme, but it breaks if Roboto is not installed locally.
> fix(Chip): remove font-family from chip Label

- scripts/seed-authors.sh
This is a very tiny fix. This hasn't been an issue for us, but it could if we ever reseeded the AUTHORS file. 
This commit makes the following change: Do not append the authors to the file. Instead overwrite that file
> fix(seed-authors): replace append with write

- src/components/Avatar.js
- src/components/Button.js
- src/components/Circular.js
- src/components/Divider.js
- src/components/Image.js
- src/components/List/ListItem.js
- src/index.js
Goal: Remove the need to create our own components simply to attach a
class name, or other identifiable attribute.
Secondary Goal: Remove classnames, which can cause styling issues, and
instead use data-smc attribute to identify the component name. Where
necessary we should use the component itself in interpolation to
actually style sub components.
This just removes the custom button component. Wrapping a component in
'styled' removes the automatic whitelisting of props that react does.
This removes the need to declare an intermediate click action and white
list the props on the button.
This is an evolving PR that will contain a lot of API updates. Each API update will be detailed here:
I decided to decompose this component into one that uses other basic building block components …
> chore(update patterns): Remove classNames

- AUTHORS
- src/components/Avatar.js
- src/components/Drawer.js
- src/components/Portal/Portal.js
Adjusts the sidebar spec to reflect the spec defined within material.
Changes:
Width is now fixed to 240px, as spec dictates. Also changes the display to inline-table for the Before/After left and right shifts, meaning the (persistent) sidebar will always take up the space it requires, as spec dictates.
https://docs-hftsbpxxmj.now.sh !
Fixes Issue #147
> Sidebar Spec Fix

- pages/chips.js
- src/components/Chip.js
Previously Chip had been written with all of its subcomponents as styled components, but the default export was not. This PR corrects that so the Chip component will have S-C methods like `extend` available to it.
> fix/chip: export chip as styled component

- .stylelintrc
- package.json
- yarn.lock
[Stylelint](https://github.com/stylelint/stylelint) is a styles linting tool with support for and from styled components.
There are handy text editor [plugins](https://github.com/stylelint/stylelint/blob/434cf4660d824e183d94d9897f9d181f64c09172/docs/user-guide/complementary-tools.md#editor-plugins) including VS Code and even _vim_
This PR adds a basic stylelint implementation as described [here](https://www.styled-components.com/docs/tooling)
*Pros*: Linting 👍 
*Cons*: --fix option is experimental, so there's a fair amount of work that would go in to the retroactive linting that would have to happen. Additionally, linting requirements increase the work that goes in to making a contribution to this repo.
My feeling is that this would be a win for this repo for all of the reasons that we …
> [RFC]style(linting): add stylelint

- pages/checkboxes.js
- src/components/Checkbox.js
- Removed classNames and passed props.className to the outer wrapper to support Component selector pattern
- Refactored icon into a single component. 
- Renamed subcomponents for simplicity and exported those along with the default export to allow for component selector styling.
> refactor(Checkbox): remove classNames, export as S-C

- pages/checkboxes.js
- src/components/Checkbox.js
API change: `defaultChecked` prop removed and replaced with a `default` prop which can accept 'checked' or 'indeterminate'. 
Should allow forms that are controlling checkboxes to reset them back to an indeterminate state.
> feat(Checkbox): improve handling of indeterminate

- pages/text-fields.js
- src/components/DropdownMenu.js
- src/components/TextField.js
#Implemented a new textfield to be used in the property details page. 
Added support for multiple browsers, as well as a11y. 
link => https://docs-wnyapgsmik.now.sh
spec link => https://material.io/guidelines/components/text-fields.html#text-fields-layout
> Implement dropdown menu

- src/components/Table/Table.js
I feel as though we should remove elevation from being on the tables. According to spec, it seems as though the table itself doesn't have elevation on it, but rather inserting the tables into cards.
Right now we have tables within cards, and it now has double elevation.
Here is the spec, with the section I'm referring to being (Tables within cards): https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards
Now Link: https://docs-sndqbfdqsj.now.sh
> refactor(Table): Remove elevation

- src/components/Snackbar.js
This is setting the Snackbar to display none if it is not yet opened. In the Merlin repo it's easy to see the error / recreate it, but in SMC it's hard to reproduce the same effect.
I'm hoping this could potentially resolve what is happening in this issue #193.
> fix(Snackbar): Remove from DOM if closed

- package.json
- src/components/FlexGrid/Column.js
- src/components/FlexGrid/Row.js
- src/contexts/ScreenSizeContext.js
- yarn.lock
A tweet by Andrew Clark https://twitter.com/acdlite/status/971598256454098944 illustrated something pretty cool with context api and creating HoC's meant to wrap functions that add additional arguments instead of props. This is much cleaner, imo.
> [RFC] refactor(Contexts): Use functional HOC

- src/components/Portal/Overlay.js
Fixes Portal Overlay to `position:fixed`. Currently if the page has
scrolled and a dialog is opened, the dialog is only shown at the top of the page.
This PR allows the dialog to scroll and take up 100% of the current
view.
https://docs-cbziuwrhqb.now.sh/dialog/
> fix(Dialog): Fix overlay to correct position

- pages/checkboxes.js
- src/components/Checkbox.js
- src/index.js
Add `checkMark` and `indeterminateMark` props so users can pass in their own checkmark icons. Refactored Checkbox component to eliminate unnecessary wrapper div. 
Now Link: https://docs-zypoftzofl.now.sh/checkboxes/
> enhancement(Checkbox): accept checkMark prop

- src/components/Divider.js
Fixes #203 
This PR fixes the console warnings that were being thrown whenever Divider was in use by removing the marginLeft attribute from the `<hr>` and moving the logic into css.
> fix(Divider): fix `marginLeft` console warning

- src/components/DropdownMenu.js
- src/components/Menu/Menu.js
- src/components/Table/Table.js
- src/components/TextField.js
This PR
- fixes underline color to match theme styles
- adds pointer on hover
- adds request close when click is registered outside of an open menu
- allows dropdown menu to be tabbed into with keyboard
Resolve #199, Resolve #197, Resolve #196, Resolve #179 
Demo: https://docs-tcqmhzveck.now.sh/text-fields/
> fix(Dropdown): update styles

- package.json
- src/contexts/ScreenSizeContext.js
- yarn.lock
This adds platform.js to check the user's platform and pass that
information along with the screen size context.
My thinking for including this in screen size context is that the consumers of screen size context are likely to be the ones that care about platform.
> feat(screensizecontext): pass platform to context

- pages/menus.js
- src/components/Menu/Menu.js
This allows us to attach an anchor element to the menu to know the position at which the menu opens up to.
This doesn't add in the fix to open it in different directions based on where it is at in the window quite yet.
Would be curious to get thoughts on this!
Now link: https://docs-exezjdowac.now.sh
> fix(Menu): Add anchor element to attach to

- src/components/Table/Table.js
Tuen sortBy into an arrow function in order to keep "this" context when
checking for props
> fix(Table): Fix SortBy

- src/components/Table/Table.js
This will help for relay connected tables where you have to fetch more data if you're expanding the rows per page.
> feat (Table): Add onRowChange callback

- src/index.js
- src/theme/ThemeProvider.js
- src/theme/defaultTheme.js
Export generateBreakpoint from the defaultTheme file in order to make
it easier to provide custom breakpoints to the theme from user land.
> feat(generateBreakpoint): export generateBreakpoit

- package.json
- src/components/Tabs/Tabs.js
* Renames Inkbar to avoid a namespace collision with the Navigation Inkbar.
* **Breaking change**: The tabs inkbar's data-smc property has been renamed to
"TabsInkBar"
> Version 0.0.46

- src/components/Dialog/Dialog.js
This fixes the styles to use the CSS template literal in hopes to resolve a testing issue with jest. There was also a missing semicolon that could cause errors. Ref: https://github.com/styled-components/jest-styled-components/issues/97#issuecomment-364169127
The ternary is necessary here, so we don't pass undefined as a classname.
> fix(Dialog): Fix styles

- pages/_document.js
- pages/snackbar.js
- src/components/Snackbar.js
- utilize withScreenSize context provider to set a prop `mobile` on xs and sm screen sizes
- `mobile` prop used for changing styles conditionally on smaller screen sizes
- add `multiline` prop to indicate that a snackbar should take up two lines instead of one. only works when `mobile` prop has been triggered
Did not add Action Button functionality to snackbar at this time.
> feat(Snackbar): Add Mobile Snackbar

- package.json
- src/components/FlexGrid/Column.js
- src/components/FlexGrid/Row.js
- src/components/Snackbar.js
- src/contexts/ScreenSizeContext.js
- yarn.lock
This removes the polyfill in favor of the real thing. There is a
breaking change in that I have reverted the 'functional hoc' style for
the withScreenSize and withRowState contexts because it comes with side
effects that are unintentional with other apis that were exposed by
react 16.3 update. Namely this means the forwardRef api.
BREAKING CHANGE:
Usage of withScreenSize/withRowState must be updated.
> refactor(Contexts): Use official React 16.3 api

- src/components/FlexGrid/Column.js
- src/components/FlexGrid/Row.js
- src/contexts/ScreenSizeContext.js
This PR fixes a bug that was breaking most of the SMC pages where Column was not able to be converted to a styled component due to some effect of returning a forwardRef instead of the actual component. Per @brad-decker, the forwardRef was only a failsafe so we're removing it for now.
> fix(Column): fix breaking changes from ScreenSizeContext

- src/components/Portal/Portal.js
This just sets `defaultProps` as a static property on `Portal` to remove the console warnings about setting `defaultProps` as an instance property.
> fix Portal console warning

- pages/icons/index.js
- src/icons/icons.js
This PR allows Icon to accept an `onClick` function. Previously, we've been wrapping the icons in divs to accommodate onClick functions.
> feat(icon): add onClick

- pages/dialog.js
- src/components/Portal/Portal.js
This prevents the body from scrolling when the dialogs are open.
> fix(Dialog): No scroll on body when open

- src/components/Menu/Menu.js
This adds support for touch events as a way to close the menu
This fixes a bug where scroll was not accounted for in calculating the
next position of the menu
> fix(Menu): touch events; scroll

- package.json
- yarn.lock
Updates react and react-dom to 16.3 and moves react to being a dev
dependency and a peer dependency (mirroring versions from
styled-components). Also moves the eslint dependency to being a
devdep. These changes facilitate using `yarn link` to develop using
local changes.
> build(react & r-dom): Move to ddeps, 16.3

- src/components/Menu/Menu.js
In the current implementation, the `anchorEl` is always covered by the menu that it opens,
and therefore cannot be clicked. When styles are passed in to override that behavior, the `anchorEl`
closes then reopens the menu by firing `onClose` then flipping the `open` value in state.
This changes that behavior so that the menu will stay closed by preventing the `onClose` method from being fired when the `anchorEl` is clicked.
> feat(menu): close by anchor

- pages/dialog.js
- src/components/Dialog/Dialog.js
- src/components/Tooltip.js
Add option to open full screen dialogs from the top and bottom of the screen
> feat(dialog): open from top/bottom

- src/components/Menu/Menu.js
- src/components/Menu/MenuItem.js
- src/helpers.js
Account for offsetParent of the anchorEl when computing the menu's
position.
Protect against accidental openings by checking that a clicked element
is an ancestor of the anchor element and not just the anchor element
itself.
> fix(Menu): find offsetParent

- src/components/Menu/Menu.js
- yarn.lock
This PR reverts a change that moved debounce out of a class method which was causing anchor positioning to not work. 
There will most likely be a follow-up PR from @AriLFrankel or myself that allows the menu anchor positioning to be set with a prop: `top-start`, `bottom-middle`, etc.
> fix(Menu): rollback breaking change

- src/components/DropdownMenu.js
This PR makes the TextField dropdown menu render its list of options from props instead of state. Previously, if the options passed to the component changed, they would only update if the component unmounted. This allows the menu options to change in response to changing props.
> fix(dropdown menu): pull options from props

- pages/menus.js
- src/components/Menu/Menu.js
Attachment styles: everyone's a little different.
Accept props for bottom and right attachments, as well as upwards and downwards opening
attachBottom: align top of menu with bottom of anchor
openUp: open the menu upwards, align the bottom of the menu with the bottom of the anchor
openLeft: open the menu leftwards, align the right of the menu with the right of the anchor
Defaults: attaches Top Left, opens Right Down
> feat(Menu): attachment styles

- src/components/Chip.js
This PR is a small iteration towards matching MD2 spec for Chip component.
This adds the correct styles for hover, focus, and clicked states. 
After discussion with @nataliaisabelle on our interpretations of the MD2 spec, these are the implemented changes:
- Chips that are clickable have a hover state, focused state, and clicked state
- MD2 clicked state is what was previously the MD1 focused state
- Chips that are removable but not clickable have a focused state but no hover state
- The Remove Icon has a hover state
- Chips that are neither clickable nor removable have none of the above
> feat(chip): update focus style

- src/components/Menu/Menu.js
This prevents the Menu component from displaying until it is in the
correct location. This fixes a behavior where the menu flashes on
screen before moving to the desired position
> fix(Menu): suppress flashing

- package.json
- src/contexts/ScreenSizeContext.js
```js
render() {
return (
<Context.Provider
value={{
...this.state,
}}
>
{this.props.children}
</Context.Provider>
);
}
```
This was the state of the render method of the context provider before I changed it. This spreading of state is an identified anti pattern by Dan Abramov because it creates a new object everytime the provider renders and triggers re-renders of all context consumers instead of only re-rendering when state re-renders. This PR includes a pre-release tag to 55-0, installable now via yarn add styled-material-components@RC
> Fix context

- src/mixins/elevation.js
- Fixes the function to add elevation depth, which was
broken by eslint.
- Buttons on buttons page have correct shadow when pressed
- Buttons on icons page have correct shadow when pressed
- Buttons on snackbar page have correct shadow when pressed
- Clickable chips have correct elevation when pressed
- Progresses #315
> Fix(elevation): Fix depth

- pages/avatars.js
- pages/bottomsheets.js
- pages/buttons.js
- pages/cards.js
- pages/checkboxes.js
- pages/drawer.js
- pages/gridlists.js
- pages/index.js
- pages/lists.js
- pages/menus.js
- pages/sliders.js
- pages/snackbar.js
- pages/tabs.js
- pages/text-fields.js
- Removes the override on some pages that set the theme primary color to a light blue. The default theme primary color will now be used in all pages.
- All pages use the purple default theme color rather than the light blue override; Note that the radio buttons on the menus page are not SMC components, so they use the browser default (which is close to the old primary color, at least on my version of Chrome)
- Progresses #315
> fix(Pages): Remove theme override

- src/components/Snackbar.js
You can no longer just plop a keyframe into a text string, you must
interpolate it with css inside of interpolations.
ok:
```js
const x = styled.div`animation: ${keyframe}`;
```
not ok:
```js
const x = styled.div`animation: ${props => props.animation &&
keyframe}`;
```
ok:
```js
const x = styled.div`animation: ${props => props.animation &&
css`${keyframe}`};
```
styled-components doesn't check what is returned from your
interpolations and run further interpolations on them.
-
-
-- The following sections are optional. Delete any that do not apply. --
-
-
- Resolves #
> fix(Snackbar): interpolate animations

- AUTHORS
- src/components/Dialog/Dialog.js
- Added prop to close Dialog on outside click.
- The Dialog box should close when a user clicks or touches outside the Dialog component
- Resolves #323
>  allow Dialog to close on outside click
